# Generated by Django 5.0 on 2024-02-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('User_name', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=50)),
                ('Phone', models.CharField(max_length=25)),
                ('Password', models.CharField(max_length=40)),
                ('Address', models.CharField(max_length=40)),
                ('Department', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'tbl_user',
            },
        ),
    ]
